### ISSUE TITLE
Just wanted to inform you that although this repo has the hacktoberfest topic, it has been excluded from the event.

### ISSUE THREAD

**Issue by Aloneking789** [fineanmol/Hacktoberfest2023#5549]

**Comment by SonolaMoyo** [comment]
Pls how is that, and where do you validate included repos for hacktober2023

**Comment by Aloneking789** [comment]
![Screenshot 2023-10-06 085142](https://github.com/fineanmol/Hacktoberfest2023/assets/116704975/b88d50a9-5c15-4ca0-90b1-5a06bcebbabd)
@SonolaMoyo 
YOU CAN VALIDATE IT IN YOUR HACKTOBER PROFILE
