### ISSUE TITLE
No Fevicon for Index page.. and title is from last year 

### ISSUE THREAD

**Issue by SEGRR** [fineanmol/Hacktoberfest2023#5652]
**There is no Favicon to index page**
pages with no favicon look quite dull.

**Title of index page says Hacktoberfest2022**
Need to change title to lates year 

**Solution**
- Using the same icon used in navbar for favicon.
- changing title to current year

**Comment by VBPMP** [comment]
please, Assign me this issue

**Comment by iammadanlal** [comment]
@SEGRR @VBPMP  Guys this repo is excluded from the hacktoberfest 2023. You can contribute to this repo [https://github.com/iammadanlal/os_salon_server](https://github.com/iammadanlal/os_salon_server) and your PR will be counted under hacktoberfest.

**Comment by ayushiGautam-0110** [comment]
please assign me this issue

**Comment by omkar7860** [comment]
please assign this issue to me i will fix it

**Comment by VBPMP** [comment]
please review my PR

**Comment by omkar7860** [comment]
i have tried to commit by making change but it giving workflow error not
getting merge

**Comment by omkar7860** [comment]
Glad to hear it!

**Comment by omkar7860** [comment]
may i know that's why it was giving workflow error??
