### ISSUE TITLE
PR's excluded from Hacktoberfest

### ISSUE THREAD

**Issue by ikunal-04** [fineanmol/Hacktoberfest2023#5656]
I made the two PR's in the repo and both of them shows excluded from hacktoberfest in my hacktoberfest profile:

![image](https://github.com/fineanmol/Hacktoberfest2023/assets/112847288/94c0ddda-1203-43e3-9297-a62987301f75)

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by iammadanlal** [comment]
@ikunal-04 @Ashima2003 Guys this repo is excluded from the hacktoberfest 2023. You can contribute to this repo [https://github.com/iammadanlal/os_salon_server](https://github.com/iammadanlal/os_salon_server) and your PR will be counted under hacktoberfest.

**Comment by ikunal-04** [comment]
Oh okay thank you @iammadanlal for clearing the doubt 👍

**Comment by Ashima2003** [comment]
okay @iammadanlal
