### ISSUE TITLE
PR not getting merged

### ISSUE THREAD

**Issue by manmohanhunjan** [fineanmol/Hacktoberfest2023#5814]
My pr is not getting merged please merge it.

I've given the star to repo too.

here's the error: Run echo "Commenting on issue/PR..."
  echo "Commenting on issue/PR..."
  comment_body="@manmohanhunjan Please Star ⭐️ the repo to earn '**_hacktober-accepted_**' label for the event."
  echo "$comment_body" | gh issue comment  --body -
  shell: /usr/bin/bash -e {0}
  env:
    COMMENT_BODY: @manmohanhunjan Please Star ⭐️ the repo to earn '**_hacktober-accepted_**' label for the event.
    GITHUB_TOKEN: 
Commenting on issue/PR...
accepts 1 arg(s), received 0
Error: Process completed with exit code 1.

**Comment by danishagarwal** [comment]
Same here!

**Comment by manmohanhunjan** [comment]
But it's not hacktober fest accepted

**Comment by kchilds1** [comment]
I'm having the exact same error with my PR
