### ISSUE TITLE
Login page,  and Java code 

### ISSUE THREAD

**Issue by Nikuunj** [fineanmol/Hacktoberfest2023#5931]
Hello, @fineanmol I would like to add some java programs and login page
Kindly assign me this issue under Hacktoberfest 2023.
I have already starred ⭐️ the repo. #5931

**Comment by Nikuunj** [comment]
Hello, @fineanmol I would like to add some trees and graphs C++ programs
Kindly assign me this issue under Hacktoberfest 2023.
I have already starred ⭐️ the repo.

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me
