### ISSUE TITLE
Basic Java-Programming & Sorting Algo

### ISSUE THREAD

**Issue by MadMax1311** [fineanmol/Hacktoberfest2023#5936]
Hello, @fineanmol I would like to add some basic java programs and sorting algo
Kindly assign me this issue under Hacktoberfest 2023.
I have already starred ⭐️ the repo.

**Comment by adinathraut** [comment]
Hey, @fineanmol I Already have solved this issue 1 parent [5c2472b](https://github.com/adinathraut/Hacktoberfest2023/commit/5c2472bb80d8d58b40d5df4a6923e907a6106e4f)
commit afb3108

**Comment by vamus092** [comment]
//solving linear search in java
//linear search in java
import java.util.Scanner;
class l_search
{
    public static void main(String args)
    {

        int c=0,a[100],x ,i;
        Scanner in=new Scanner(System.in);
        System.out.println(" ENTER THE LIMIT OF THE ARRAY:");
        int n=in.nextInt();
        for( i=0;i<n;i++)
        {
            a[i]=in.nextInt();
        }
        System.out.println("ENTER THE NUMBER TO BE SEARCHED:");
        x=in.nextInt();
        for( i=0;i<n;i++)
        {
            if(a[i]==x)
            { c=1;
                break;
            }
        }
        if(c==1)
            System.out.println("NUMBER FOUND");
        else
            System.out.println("NUMBER NOT FOUND");
    }
}
