### ISSUE TITLE
I would like to add binary search in python

### ISSUE THREAD

**Issue by saurabh22111999** [fineanmol/Hacktoberfest2023#6088]
**Is your feature request related to a problem? Please describe.**
The problem of efficiently finding a specific target value within a sorted collection of data, typically an array or a list.

**Describe the solution you'd like**
Binary search is a popular algorithm used to efficiently locate a specific value within a sorted collection (usually an array or list). It works by repeatedly dividing the search interval in half until the desired value is found or it's determined that the value does not exist in the collection.

**Describe alternatives you've considered**
An alternative approach to searching for a target value in an unsorted collection (array or list) is to use a linear search, also known as a sequential search.

**Additional context**
Binary Search Complexity:

Time Complexity: O(log n)
Space Complexity: O(1)
Binary search is highly efficient, especially for large datasets, because it divides the dataset in half at each step. As a result, the time it takes to find a target value grows logarithmically with the size of the dataset. In the worst case, it takes a relatively small number of comparisons to find the target.

Linear Search Complexity:

Time Complexity: O(n)
Space Complexity: O(1)
Linear search involves checking each element in the dataset one by one until the target is found or the end of the dataset is reached. The number of comparisons increases linearly with the size of the dataset. In the worst case, you might have to check every element in the collection.

**Comment by anushka9555** [comment]
Hi. I am a medium-level python coder. Please assign this task to me. Thank you

**Comment by HarshitaShrivas66** [comment]
Hello, I would really appreciate contributing to this repository by adding a code
@saurabh22111999  please assign this task to me.
thank you

**Comment by kingSSG** [comment]
thank you for the opportunity
