### ISSUE TITLE
merge all python PRs in one shot

### ISSUE THREAD

**Issue by RoshanJ20** [fineanmol/Hacktoberfest2023#6510]
A simple python program that merges all python PRs in a single run. Thereby saving @fineanmol 's time.

**Comment by Vishnu9535** [comment]
can u assign me this

**Comment by SwayamSahu** [comment]
Hi there! I'm Swayam and I'm interested in working on this issue. I've read through the problem description and believe I can help resolve it. Would it be possible for me to take on this issue? I'd appreciate any guidance or permissions required to get started. Thanks!

**Comment by RoshanJ20** [comment]
not completed

**Comment by Vishnu9535** [comment]
bro i just completed solving this issue
