### ISSUE TITLE
More button

### ISSUE THREAD

**Issue by dubeysuraj864** [fineanmol/Hacktoberfest2023#6780]
More button when hovering little width increases and unhover decreases and the text should light when the background dark red and vice versa.

**Comment by aliabbasnagari** [comment]
Assign it to me.

**Comment by aliabbasnagari** [comment]
I did a pull request but I am getting:

echo "Commenting on issue/PR..."
  comment_body="@aliabbasnagari Please Star ⭐️ the repo to earn '**_hacktober-accepted_**' label for the event."
  echo "$comment_body" | gh issue comment  --body -
  shell: /usr/bin/bash -e {0}
  env:
    COMMENT_BODY: @aliabbasnagari Please Star ⭐️ the repo to earn '**_hacktober-accepted_**' label for the event.
    GITHUB_TOKEN: 
Commenting on issue/PR...
accepts 1 arg(s), received 0

**Comment by aliabbasnagari** [comment]
Here is link to the pull request:
https://github.com/fineanmol/Hacktoberfest2023/actions/runs/6591640220/job/17910664316?pr=6831

**Comment by NIRMAL1508** [comment]
Hey, I am interested to fix this issue

**Comment by 1Amit-singh** [comment]
Resolving the load more btn bug
