### ISSUE TITLE
Create HTML CSS & Javascript Clock

### ISSUE THREAD

**Issue by Rohitsonvane88** [fineanmol/Hacktoberfest2023#6848]
**Is your feature request related to a problem? Please describe.**
Design Working Analog Clock with help of html, css, javascript

**Describe the solution you'd like**
create index.html file and start designing clock with help of css properties and js functionality

**Describe alternatives you've considered**

**Additional context**

**Comment by Rohitsonvane88** [comment]
I am working on this issue

**Comment by Babuprasanth27** [comment]
Hey, I am interested to fix this issue. would you please assign to me

**Comment by NIRMAL1508** [comment]
Hey, I am interested to fix this issue

**Comment by muhammadammar33** [comment]
Hey , I have done this task.
Assign it to me.

**Comment by amreshrai2002** [comment]
Hey, I am interested to fix this issue. would you please assign to me

**Comment by VBPMP** [comment]
please assign this issue to me

**Comment by itzanway** [comment]
Please assign this task to me under hacktoberfest
